version: "3.7"

services:
  snippetbox:
    image: snippetbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./:/go/src/github.com/SolBaa/snippetbox
    command: gowatch
    networks:
      - default
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: web
      MYSQL_PASSWORD: sol1234
      MYSQL_DATABASE: snippetbox
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
    ports:
      - 3307:3306
